version: "3"

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python core_app/manage.py runserver 0.0.0.0:8000"
  # db:
  #   image: mariadb