version: "3"

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./app:/app
    # environment:
    #   SERVICE_PRECONDITION: "db:3306"
    command: 
       ["core_app/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
      


  db:
    image: mariadb
    volumes:
      - ./db:/db
      - ./mariadb
    ports:
        - "3306:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: "1234"
        MYSQL_DATABASE: db
        MYSQL_USER: "mariadb_user"
        MYSQL_PASSWORD: "mariadb_pass"
    healthcheck:
        interval: 5s
        retries: 100 
    # volumes:
    #   - ./mariadb:/var/lib/mysql

  redis:
    image: redis


# -- docker-compose exec db mysqldump db > db/backup-file.sql -u root --password=1234
# mysql> source db/backup-file.sql
